import { ApplicationModel, ApplicationType, Color, Dimensions, Singleton } from "objects.slint";
import { ScrollView } from "std-widgets.slint";

export component ApplicationCard inherits Rectangle {
    callback clicked(ApplicationModel);
    in property <ApplicationModel> application;

    width: 164px;
    height: 200px;
    background: area.has-hover ? Color.secondary : Color.tertiary;
    border-radius: Dimensions.medium;

    animate background { duration: 150ms; }

    area := TouchArea {
        clicked => {
            root.clicked(root.application);
        }
    }

    function get-display-name() -> string {
        if application.type == ApplicationType.installed && application.has-icon {
            return "";
        }
        return application.display-name.is-empty ? application.name : application.display-name;
    }

    Text {
        y: parent.height * 3 / 4;
        width: parent.width - Dimensions.huge;
        text: root.get-display-name();
        horizontal-alignment: center;
        color: Color.foreground;
        font-size: Dimensions.font-big;
        overflow: elide;
    }

    Image {
        width: application.type == ApplicationType.installed && application.has-icon ? parent.width : 48px;
        height: application.type == ApplicationType.installed && application.has-icon ? parent.height : 48px;
        source: application.icon;
        colorize: application.type == ApplicationType.installed && application.executable.is-empty ? #00000000 : Color.foreground;
    }

    if application.executable == "" && application.type == ApplicationType.installed: Rectangle {
        background: #00000050;

        Text {
            text: "NOT INSTALLED";
            color: Color.primary;
        }
    }

    // We create another rectangle for the outline to ensure that it is drawn *over* the image
    Rectangle {
        border-radius: Dimensions.medium;
        border-width: area.has-hover || application.id == Singleton.active-application-id ? Dimensions.small : 0px;
        border-color: Color.brand;

        animate border-width { duration: 150ms; }
    }
}

export component ApplicationContainer inherits ScrollView {
    viewport-width: 180px * Singleton.applications.length + Dimensions.huge * 3;
    viewport-height: 200px;
    horizontal-scrollbar-policy: always-off;
    mouse-drag-pan-enabled: true;

    for i in Singleton.applications.length: ApplicationCard {
        x: i * 180px;
        application: Singleton.applications[i];

        clicked(application) => {
            Singleton.select-application(application);
        }
    }
}
