import "../assets/fonts/ArchivoBlack/ArchivoBlack-Regular.ttf";

import { ScrollView, LineEdit } from "std-widgets.slint";

import { SlintAttribution } from "attribution.slint"; 
import { ProcessSlint, ProcessView } from "processes.slint"; 
import { ProfileSlint, ProfileView } from "profiles.slint";
import { EditableField, EditableType, PrettyButton, Title } from "text.slint";

export component AppWindow inherits Window {
    callback name-edit();
    callback image-edit();
    callback exec-edit();

    callback forget-app();
    callback restart-ghub();

    callback add-app();
    callback add-process(ProcessSlint);

    callback dialog-lock-release();
    callback dialog-lock-acquire();
    dialog-lock-release() => {
        dialog-lock = false;
    }
    dialog-lock-acquire() => {
        dialog-lock = true;
    }

    in-out property <[ProfileSlint]> profiles;
    in-out property <[ProcessSlint]> processes;
    in-out property <string> active-profile;
    in-out property <string> profile-field-name;
    in-out property <string> profile-field-img;
    in-out property <string> profile-field-exec;

    out property <string> search-text: search-box.text;

    property <bool> dialog-lock: false;
    
    width: 960px;
    height: 540px;

    title: "GProfiles";
    icon: @image-url("../assets/app.ico");
    background: #000000;

    scope := FocusScope {}

    TouchArea {
        clicked => {
            scope.focus();
        }
    }

    Title {
        x: 50px;
        y: 20px;
        text: "ADD APPLICATION";
    }

    Title {
        x: 500px;
        y: 20px;
        text: "GAME PROFILES";
    }

    Title {
        x: 15px;
        y: 275px;
        text: "DETECTED APPLICATIONS";
    }

    search-box := LineEdit {
        x: 20px;
        y: 300px;
        width: 200px;
        height: 20px;
        placeholder-text: "Search";
    }

    Rectangle {
        x: 240px;
        y: 280px;
        width: 710px;
        height: 250px;

        background: #3b3b3b;
        border-radius: 5px;

        // Slint's Royalty-free license requires me
        // to include this somewhere that can be seen.
        SlintAttribution {
            x: -75px;
            y: 70px;
        }

        EditableField {
            x: 20px;
            y: 25px;
            title: "PROFILE NAME";
            field <=> root.profile-field-name;
            type: EditableType.text;
            clicked => {

                root.name-edit();
            }
        }

        EditableField {
            x: 20px;
            y: 85px;
            title: "IMAGE PATH";
            field: root.profile-field-img;
            type: EditableType.file;
            clicked => {
                root.image-edit();
            }
        }

        EditableField {
            x: 20px;
            y: 145px;
            title: "EXECUTABLE PATH";
            field: root.profile-field-exec;
            type: EditableType.file;
            clicked => {
                root.exec-edit()
            }
        }

        forget-button := PrettyButton {
            x: 20px;
            y: 205px;

            text: "FORGET";
            icon: @image-url("../assets/material_icons/delete_24.png");
            background: forget-area.has-hover ? #ff2e2e : #e00d0d;

            animate background {
                duration: 150ms;
            }

            forget-area := TouchArea {
                clicked => {
                    root.forget-app();
                }
            }
        }

        PrettyButton {
            x: 500px;
            y: 205px;
            width: 190px;

            text: "RESTART LGHUB";
            icon: @image-url("../assets/material_icons/refresh_24.png");
            background: apply-area.has-hover ? #999999 : #666666;

            animate background {
                duration: 150ms;
            }

            apply-area := TouchArea {
                clicked => {
                    root.restart-ghub();
                }
            }
        }
    }
    
    ProfileView {
        y: 50px;
        x: 50px;

        active: active-profile;
        profile: {
            icon: @image-url("../assets/material_icons/add_circle_48.png")
        };

        TouchArea {
            clicked => {
                root.add-app();
            }
        }

        Title {
            y: 160px;
            text: "NEW";
            color: #ffffff;
        }
    }

    // Profiles
    ScrollView {
        property <physical-length> spacing: 200px;
        property <int> num-profiles: profiles.length;

        x: 250px;
        y: 50px;
        width: 700px;
        height: 240px;
        viewport-width: spacing * num-profiles;
        viewport-height: 210px;

        for i in num-profiles : Rectangle {
            x: i * spacing;
            width: 150px;
            height: 210px;

            ProfileView {
                profile: profiles[i];
                active: root.active-profile;
                selected => {
                    if !root.dialog-lock {
                        root.active-profile = self.profile.id;
                        root.profile-field-name = self.profile.name;
                        root.profile-field-img = self.profile.image-path;
                        root.profile-field-exec = self.profile.executable;
                    }
                }
            }
        }
    }
    
    // Processes
    ScrollView {
        property <physical-length> spacing: 35px;
        property <int> num-processes: processes.length;

        x: -380px;
        y: 330px;
        width: 630px;
        height: 200px;
        viewport-height: num-processes * spacing;

        for i in num-processes : Rectangle {
            x: 400px;
            y: i * spacing;
            height: 30px;
            width: 200px;

            ProcessView {
                process: processes[i];
                clicked(process) => {
                    root.add-process(process);
                }
            }
        }
    }
}
