import { Color, Dimensions, Singleton } from "objects.slint";
import { ProcessContainer } from "processes.slint";
import { Title } from "components.slint";
import { ApplicationCard, ApplicationContainer } from "applications.slint";
import { ApplicationEditor } from "editor.slint";

export { Color, Singleton }

export component App inherits Window {
    title: "GProfiles";
    icon: @image-url("../assets/app.ico");
    min-width: 960px;
    min-height: 540px;
    background: Color.background;

    scope := FocusScope { }

    TouchArea {
        clicked => {
            scope.focus();
        }
    }

    new-card := ApplicationCard {
        x: Dimensions.huge * 3;
        y: Dimensions.huge * 3;
        application: {
            name: "NEW",
            icon: @image-url("../assets/add.png"),
            has-icon: false,
        };

        clicked => {
            Singleton.create-application();
        }
    }

    profiles := Title {
        x: new-card.width + new-card.x * 2;
        y: Dimensions.huge;
        width: root.width - self.x - Dimensions.huge;
        text: "GAME PROFILES";
    }

    application-container := ApplicationContainer {
        x: profiles.x - Dimensions.large;
        y: profiles.y + profiles.height + Dimensions.medium;
        width: profiles.width + Dimensions.huge;
        height: 200px;
    }

    Rectangle {
        x: application-container.width + application-container.x - self.width + Dimensions.small;
        y: application-container.y;
        width: Dimensions.huge * 6;
        height: application-container.height;
        background: @linear-gradient(-90deg, #000000, #00000000);
    }

    processes := ProcessContainer {
        x: Dimensions.medium;
        y: root.min-height / 2;
        width: root.min-width / 4;
        height: root.min-height / 2 - Dimensions.medium;
    }

    ApplicationEditor {
        x: processes.x + processes.width;
        y: processes.y;
        width: root.width - self.x - Dimensions.huge;
        height: root.height - self.y - Dimensions.huge;
    }
}
