import { AboutSlint } from "std-widgets.slint";

export component SlintAttribution inherits Rectangle {
    AboutSlint {
        height: 20px;
    }

    AboutSlint {
        x: 110px;
        y: 70px;
        height: 20px;
    }

    Rectangle {
        x: 410px;
        y: 80px;
        width: 110px;
        height: 50px;
        
        background: #3b3b3b;
    }

    Rectangle {
        x: 300px;
        y: 180px;
        width: 110px;
        height: 50px;

        background: #000000;
    }
}
