import { Color, Dimensions } from "objects.slint";
import { LineEdit } from "std-widgets.slint";

export enum FieldInputType { editable, selectable, readable}
export enum Location { top, bottom, left, right }

export component CollapsableContainer inherits Rectangle {
    in property <string> name;
    in-out property <bool> is-collapsed: true;

    TouchArea {
        clicked => {
            root.is-collapsed = !root.is-collapsed;
        }
    }

    image := Image {
        x: Dimensions.small;
        width: Dimensions.large;
        height: Dimensions.large;
        colorize: Color.secondary;
        source: @image-url("../assets/arrow.png");
        rotation-angle: root.is-collapsed ? 0 : 90deg;

        animate rotation-angle { duration: 150ms; }
    }

    text := Text {
        x: image.x + image.width + Dimensions.small;
        text: name;
        color: Color.secondary;
        font-weight: Dimensions.font-bold;
    }

    Rectangle {
        x: text.x + text.width + Dimensions.small;
        width: parent.width - self.x - Dimensions.large;
        height: Dimensions.small;
        background: Color.secondary;
        border-radius: Dimensions.medium;
    }
}

export component DropdownMenu inherits Rectangle {
    public pure function is-visible() -> bool {
        return !self.is-collapsed;
    }

    public function show() {
        self.set-visibility(true)
    }

    public function hide() {
        self.set-visibility(false);
    }

    public function set-visibility(visible: bool) {
        self.is-collapsed = !visible;
    }

    in-out property <string> selected;
    out property <physical-length> left-padding: image.width + Dimensions.small * 2;
    private property <bool> is-collapsed: true;

    height: text.height + Dimensions.medium;
    background: area.has-hover ? Color.background-accent : Color.background;

    border-radius: Dimensions.medium;
    border-bottom-left-radius: !root.is-visible() ? Dimensions.medium : 0px;
    border-bottom-right-radius: !root.is-visible() ? Dimensions.medium : 0px;

    animate border-bottom-left-radius, border-bottom-right-radius, background { duration: 150ms; }

    area := TouchArea {
        clicked => {
            root.set-visibility(!root.is-visible());
        }
    }

    text := Text {
        x: image.width + Dimensions.small * 2;
        width: parent.width - self.x * 2;
        text: selected;
        color: Color.foreground;
        overflow: elide;
    }

    image := Image {
        x: Dimensions.small;
        width: Dimensions.large;
        height: Dimensions.large;
        colorize: Color.foreground;
        source: @image-url("../assets/arrow.png");
        rotation-angle: root.is-collapsed ? 0 : 90deg;

        animate rotation-angle { duration: 150ms; }
    }
}

export component HoverableComponent inherits Rectangle {
    callback clicked <=> area.clicked;
    callback double-clicked <=> area.double-clicked;

    in property <color> hover;
    in property <color> default;
    in property <duration> duration: 150ms;

    animate background { duration: duration; }

    background: area.has-hover ? hover : default;
    area := TouchArea { }
}

export component Title inherits Text {
    color: Color.brand;
    font-size: Dimensions.font-title;
    font-weight: Dimensions.font-bold;
    horizontal-alignment: center;
}

export component ImageButton {
    callback clicked <=> comp.clicked;
    callback double-clicked <=> comp.double-clicked;

    in property <image> icon;
    in property <string> text;
    in property <Location> icon-position: Location.left;

    in property <color> background;
    in property <color> hover;
    in property <length> corner-radius;

    in property <length> font-size;
    in property <int> font-weight;

    width: txt.width + img.width + Dimensions.large;

    comp := HoverableComponent {
        default: root.background;
        hover: root.hover;
        border-radius: root.corner-radius;
    }

    img := Image {
        x: (icon-position == Location.right ? txt.width + Dimensions.small : 0) + Dimensions.small;
        height: parent.height;
        source: root.icon;
    }

    txt := Text {
        x: (icon-position == Location.left ? img.width + Dimensions.small : 0) + Dimensions.small;
        text: root.text;
        font-size: root.font-size;
        font-weight: root.font-weight;
    }
}

export component Field inherits Rectangle {
    callback clicked <=> area.clicked;
    callback double-clicked <=> area.double-clicked;
    callback accepted <=> field.accepted;

    in property <string> name;
    in property <string> placeholder;
    in property <FieldInputType> input-type;
    in-out property <string> value;

    height: title.height + field.height;

    title := Title {
        x: 0;
        y: 0;
        text: name;
    }

    area := TouchArea {
        x: 0;
        y: title.height;
        width: parent.width;
        height: field.height;

        field := LineEdit {
            x: 0px;
            y: 0px;
            width: parent.width;

            text <=> value;
            placeholder-text: root.placeholder;
            read-only: input-type == FieldInputType.selectable;
            enabled: input-type != FieldInputType.readable;
        }
    }
}
