import { AboutSlint } from "std-widgets.slint";

export component SlintAttribution inherits Rectangle {
    AboutSlint {
        height: 20px;
    }

    AboutSlint {
        x: 110px;
        y: 70px;
        height: 20px;
    }

    Rectangle {
        x: 410px;
        y: 80px;
        width: 110px;
        height: 50px;
        background: #3b3b3b;
    }

    Rectangle {
        y: 180px;
        height: 10px;
        width: 80px;
        background: #000000;
    }
}

export component HoverableComponent inherits Rectangle {
    callback clicked();

    in property <color> hover;
    in property <color> default;
    in property <duration> duration: 150ms;

    animate background { duration: duration; }

    background: area.has-hover ? hover : default;
    area := TouchArea {
        clicked => {
            root.clicked()
        }
    }
}
