import {
    ApplicationModel,
    ApplicationType,
    Color,
    Dimensions,
    KeybindModel,
    ProfileModel,
    Singleton,
} from "objects.slint";
import {
    CollapsableContainer,
    DropdownMenu,
    Field,
    FieldInputType,
    HoverableComponent,
    ImageButton,
} from "components.slint";
import { AboutSlint, Button, ScrollView } from "std-widgets.slint";

component Tab inherits Rectangle {
    in property <string> name;
    in-out property <string> active-tab;

    public pure function is-active() -> bool {
        return self.name == self.active-tab;
    }

    width: 96px;
    height: 32px;
    background: touch-area.has-hover && !self.is-active() ? Color.primary : Color.secondary;

    border-color: Color.tertiary;
    border-width: Dimensions.small;
    border-top-left-radius: Dimensions.medium;
    border-top-right-radius: Dimensions.medium;

    animate background { duration: 150ms; }

    touch-area := TouchArea {
        clicked => {
            root.active-tab = root.name;
        }
    }

    Text {
        text: name;
        color: root.is-active() ? Color.brand : #000000;
        font-weight: 900;
    }

    Rectangle {
        y: root.height - root.border-width - (is-active() ? 1px : 0px);
        width: root.width - (2 * root.border-width);
        height: root.border-width + (is-active() ? 2px : 0px);
        background: root.is-active() ? root.background : root.border-color;
    }
}

component KeybindsContainer inherits Rectangle {
    background: Color.background;
    border-radius: Dimensions.medium;

    ScrollView {
        private property <physical-length> keybind-height: 40px;

        viewport-width: parent.width;
        viewport-height: (Singleton.keybinds.length + 1) * (self.keybind-height + Dimensions.medium) + Dimensions.medium;
        vertical-scrollbar-policy: always-off;
        mouse-drag-pan-enabled: true;

        HoverableComponent {
            y: Singleton.keybinds.length * (keybind-height + Dimensions.medium) + Dimensions.medium;
            width: parent.width - Dimensions.huge;
            height: keybind-height;

            hover: Color.background-accent;
            default: Color.background;

            border-color: Color.foreground;
            border-width: Dimensions.small / 2;
            border-radius: Dimensions.medium;

            Image {
                x: Dimensions.large;
                width: parent.height - Dimensions.large;
                height: parent.height - Dimensions.large;
                source: @image-url("../assets/add.png");
                colorize: Color.foreground;
            }

            Text {
                x: parent.height + Dimensions.medium;
                text: "Add new keybind...";
                color: Color.foreground;
            }

            clicked => {
                Singleton.create-keybind();
            }
        }

        for i in Singleton.keybinds.length: Rectangle {
            private property <KeybindModel> keybind: Singleton.keybinds[i];

            y: i * (keybind-height + Dimensions.medium) + Dimensions.medium;
            width: parent.width - Dimensions.huge;
            height: keybind-height;

            input-rect := HoverableComponent {
                private property <string> key;
                x: Dimensions.small;
                width: parent.width / 3 - Dimensions.huge;
                default: Color.secondary;
                hover: Color.secondary-accent;
                border-radius: Dimensions.medium;
                forward-focus: input-scope;

                Text {
                    text: parent.key;
                    font-size: Dimensions.font-big;
                    font-weight: Dimensions.font-bold;
                }

                input-scope := FocusScope {
                    focus-gained(reason) => {
                        if (reason == FocusReason.pointer-click) {
                            parent.key = "..."
                        }
                    }

                    key-pressed(event) => {
                        let char = Singleton.keybind-mapper(event.text);
                        Singleton.input-clicked(keybind, char);
                        parent.key = char;
                        input-scope.clear-focus();
                        accept
                    }
                }
            }

            arrow-img := Image {
                x: input-rect.x + input-rect.width + Dimensions.medium;
                width: parent.height - Dimensions.huge;
                height: parent.height - Dimensions.huge;
                source: @image-url("../assets/arrow.png");
                colorize: Color.foreground;
            }

            output-rect := HoverableComponent {
                private property <string> key;

                x: arrow-img.x + arrow-img.width + Dimensions.medium;
                width: parent.width / 3 - Dimensions.huge;

                default: Color.secondary;
                hover: Color.secondary-accent;
                border-radius: Dimensions.medium;
                forward-focus: output-scope;

                Text {
                    text: parent.key;
                    font-size: Dimensions.font-big;
                    font-weight: Dimensions.font-bold;
                }

                output-scope := FocusScope {
                    focus-gained(reason) => {
                        if (reason == FocusReason.pointer-click) {
                            parent.key = "..."
                        }
                    }

                    focus-lost(reason) => {
                        if (parent.key == "...") {
                            parent.key = ""
                        }
                    }

                    key-pressed(event) => {
                        let char = Singleton.keybind-mapper(event.text);
                        Singleton.output-clicked(keybind, char);
                        parent.key = char;
                        output-scope.clear-focus();
                        accept
                    }
                }
            }

            HoverableComponent {
                x: output-rect.x + output-rect.width + Dimensions.huge;
                width: parent.width / 3 - Dimensions.huge * 2;

                default: Color.danger;
                hover: Color.danger-accent;
                border-radius: Dimensions.medium;

                Image {
                    width: parent.width - Dimensions.huge;
                    source: @image-url("../assets/delete.png");
                }

                clicked => {
                    Singleton.delete-keybind(keybind);
                }
            }
        }
    }
}

component DetailsContainer inherits Rectangle {
    Field {
        x: Dimensions.huge * 2;
        y: Dimensions.large;
        width: parent.width - self.x - keybinds.width - keybinds.y - Dimensions.huge;
        name: "Name";
        value <=> Singleton.name;
        input-type: Singleton.name == "APPLICATION_NAME_DESKTOP" ? FieldInputType.readable : FieldInputType.editable;

        accepted(text) => {
            Singleton.change-name(text)
        }
    }

    Field {
        x: Dimensions.huge * 2;
        y: parent.height / 2 - self.height + Dimensions.large * 2;
        width: parent.width - self.x - keybinds.width - keybinds.y - Dimensions.huge;
        name: "Image";
        value <=> Singleton.image;
        input-type: Singleton.active-application-type == ApplicationType.custom ? FieldInputType.selectable : FieldInputType.readable;

        clicked => {
            if (self.input-type == FieldInputType.readable) {
                Singleton.change-image()
            }
        }

        double-clicked => {
            Singleton.change-image()
        }
    }

    Field {
        x: Dimensions.huge * 2;
        y: parent.height - self.height - Dimensions.huge;
        width: parent.width - self.x - keybinds.width - keybinds.y - Dimensions.huge;
        name: "Executable";
        value <=> Singleton.executable;
        input-type: Singleton.active-application-type == ApplicationType.custom ? FieldInputType.selectable : FieldInputType.readable;

        clicked => {
            if (self.input-type == FieldInputType.readable) {
                Singleton.change-executable()
            }
        }

        double-clicked => {
            Singleton.change-executable()
        }
    }

    keybinds := KeybindsContainer {
        y: Dimensions.huge;
        x: parent.width - self.width - Dimensions.huge;
        width: parent.width * 40%;
        height: parent.height - self.y - Dimensions.huge;
    }
}

component ProfileViewerContainer inherits Rectangle {
    background: Color.background;
    border-radius: Dimensions.medium;

    ScrollView {
        private property <physical-length> profile-height: 64px;

        viewport-width: parent.width;
        viewport-height: (Singleton.profiles.length + 1) * (self.profile-height - Dimensions.medium);
        vertical-scrollbar-policy: always-off;
        mouse-drag-pan-enabled: true;

        for i in Singleton.profiles.length: HoverableComponent {
            private property <ProfileModel> profile: Singleton.profiles[i];

            y: i * (profile-height + Dimensions.medium) + Dimensions.medium;
            width: parent.width - Dimensions.huge;
            height: profile-height;

            default: Color.tertiary;
            hover: Color.tertiary-accent;
            border-radius: Dimensions.medium;
            border-width: Dimensions.small;
            border-color: profile.id == Singleton.profile-id ? Color.brand : self.background;

            name-text := Text {
                x: Dimensions.large;
                y: Dimensions.large;
                width: parent.width - self.x * 4;
                text: profile.display-name.is-empty ? profile.name : profile.display-name;
                color: Color.foreground;
                font-size: Dimensions.font-big + Dimensions.small;
                overflow: elide;
            }

            Text {
                x: Dimensions.large;
                y: Dimensions.huge + name-text.height;
                width: parent.width - self.x * 2;
                text: profile.id;
                color: Color.primary;
                overflow: elide;
            }

            if profile.active: Rectangle {
                x: parent.width - parent.x - Dimensions.huge;
                y: Dimensions.medium;
                width: Dimensions.huge;
                height: Dimensions.huge;
                background: Color.active;
                border-radius: 50px;
            }

            clicked => {
                Singleton.select-profile(profile)
            }
        }
    }
}

component ProfilesContainer inherits Rectangle {
    private property <physical-length> item-height: Dimensions.large * 2;

    viewer := ProfileViewerContainer {
        y: Dimensions.huge;
        x: Dimensions.huge;
        width: parent.width * 40%;
        height: parent.height - self.y - Dimensions.huge;
    }

    name := Field {
        x: viewer.x + viewer.width + Dimensions.huge;
        y: viewer.y;
        width: parent.width - self.x - Dimensions.huge;

        name: "Name";
        value <=> Singleton.profile-name;
        input-type: Singleton.profile-name == "PROFILE_NAME_DEFAULT" ? FieldInputType.readable : FieldInputType.editable;

        accepted(text) => {
            Singleton.name-profile(text)
        }
    }

    dropdown := DropdownMenu {
        x: viewer.x + viewer.width + Dimensions.huge;
        y: name.height + name.y + Dimensions.huge + Dimensions.small;
        width: parent.width - self.x - Dimensions.huge * 1.5 - duplicate.width;
        height: root.item-height;
        selected <=> Singleton.profile-app-name;
    }

    Rectangle {
        x: dropdown.x;
        y: dropdown.y + dropdown.height;
        width: dropdown.width;
        height: dropdown.is-visible() ? parent.height - self.y - delete.height - Dimensions.huge : 0px;
        animate height { duration: 150ms; }

        ScrollView {
            width: parent.width;
            height: parent.height;
            viewport-width: parent.width;
            viewport-height: Singleton.applications.length * root.item-height;
            vertical-scrollbar-policy: always-off;

            for i in Singleton.applications.length: HoverableComponent {
                private property <ApplicationModel> application: Singleton.applications[i];

                y: i * root.item-height;
                width: parent.width;
                height: root.item-height;

                default: Color.background;
                hover: Color.background-accent;
                border-bottom-left-radius: i == Singleton.applications.length - 1 ? Dimensions.medium : 0;
                border-bottom-right-radius: i == Singleton.applications.length - 1 ? Dimensions.medium : 0;

                Text {
                    x: dropdown.left-padding;
                    width: parent.width - self.x * 2;
                    text: application.display-name.is-empty ? application.name : application.display-name;
                    color: Color.foreground;
                    overflow: elide;
                }

                clicked => {
                    Singleton.profile-app-name = application.display-name.is-empty ? application.name : application.display-name;
                    Singleton.profile-app-id = application.id;
                    dropdown.hide();
                }
            }
        }
    }

    duplicate := ImageButton {
        x: parent.width - self.width - Dimensions.huge;
        y: name.height + name.y + Dimensions.huge;
        height: 28px;

        icon: @image-url("../assets/copy.png");
        text: "Duplicate";

        corner-radius: Dimensions.small;
        font-size: Dimensions.font-big;
        font-weight: Dimensions.font-bold;
        background: Color.primary;
        hover: Color.primary-accent;

        clicked => {
            Singleton.duplicate-profile(Singleton.profile-app-id)
        }
    }

    delete := ImageButton {
        x: parent.width - self.width - Dimensions.huge;
        y: parent.height - self.height - Dimensions.huge;
        height: 28px;
        icon: @image-url("../assets/delete.png");
        text: "Delete";

        corner-radius: Dimensions.small;
        font-size: Dimensions.font-big;
        font-weight: Dimensions.font-bold;
        background: Color.danger;
        hover: Singleton.profile-name == "PROFILE_NAME_DEFAULT" ? Color.danger : Color.danger-accent;

        clicked => {
            Singleton.delete-profile()
        }
    }
}

component AdvancedContainer inherits Rectangle {
    Field {
        x: Dimensions.huge;
        y: author.y;
        width: parent.width - author.width - self.x * 3;
        name: "Logitech settings location";
        value: Singleton.settings-path;
        input-type: FieldInputType.selectable;

        double-clicked => {
            Singleton.select-settings()
        }
    }

    Text {
        x: Dimensions.huge;
        y: restart.y - restart.height;
        text: "DANGER ZONE";
        color: Color.danger;
        font-size: Dimensions.font-big;
        font-weight: Dimensions.font-bold;
    }

    restart := ImageButton {
        x: Dimensions.huge;
        y: delete.y - delete.height - Dimensions.huge;
        height: 28px;
        icon: @image-url("../assets/refresh.png");
        text: "Restart LGHUB";

        corner-radius: Dimensions.small;
        font-size: Dimensions.font-big;
        font-weight: Dimensions.font-bold;
        background: Color.primary;
        hover: Color.primary-accent;

        clicked => {
            Singleton.restart-lghub()
        }
    }

    delete := ImageButton {
        x: Dimensions.huge;
        y: parent.height - self.height - Dimensions.huge;
        height: 28px;
        icon: @image-url("../assets/delete.png");
        text: "Delete Application";

        corner-radius: Dimensions.small;
        font-size: Dimensions.font-big;
        font-weight: Dimensions.font-bold;
        background: Color.danger;
        hover: Singleton.active-application-type == ApplicationType.custom ? Color.danger-accent : Color.danger;

        clicked => {
            if (Singleton.active-application-type == ApplicationType.custom) {
                Singleton.delete-application();
            }
        }
    }

    author := Text {
        x: parent.width - self.width - Dimensions.huge;
        y: self.height;

        text: "Made by Lee";
        color: Color.brand;
        font-size: Dimensions.font-big;
        font-weight: Dimensions.font-bold;
    }

    version := Text {
        x: parent.width - self.width - Dimensions.huge;
        y: author.height + author.y;

        text: "v1.0.0";
        color: Color.tertiary;
        font-size: Dimensions.font-big;
        font-weight: Dimensions.font-bold;
    }

    github := ImageButton {
        x: parent.width - self.width - Dimensions.huge;
        y: version.height + version.y + Dimensions.medium;
        height: 28px;

        text: "GitHub";
        icon: @image-url("../assets/github.png");

        corner-radius: Dimensions.small;
        font-size: Dimensions.font-big;
        font-weight: Dimensions.font-bold;
        background: Color.foreground;
        hover: Color.primary;

        clicked => {
            Singleton.open-github()
        }
    }

    AboutSlint {
        x: parent.width - self.width - Dimensions.small;
        y: github.height + github.y + Dimensions.huge;
        width: 128px;
        height: 128px;
    }
}

export component ApplicationEditor inherits Rectangle {
    private property <string> active-tab: tabs[0];
    private property <[string]> tabs: ["Details", "Profiles", "Advanced"];

    background-item := Rectangle {
        y: 28px;
        height: parent.height - self.y;
        background: Color.secondary;
        border-radius: Dimensions.medium;
        border-width: Dimensions.small;
        border-color: Color.tertiary;
    }

    for index in tabs.length: Tab {
        x: 96px * index + Dimensions.huge * 2;
        y: 0;
        name: tabs[index];
        active-tab <=> root.active-tab;
    }

    if self.active-tab == "Details": DetailsContainer {
        x: background-item.x;
        y: background-item.y;
        width: background-item.width;
        height: background-item.height;
    }

    if self.active-tab == "Advanced": AdvancedContainer {
        x: background-item.x;
        y: background-item.y;
        width: background-item.width;
        height: background-item.height;
    }

    if self.active-tab == "Profiles": ProfilesContainer {
        x: background-item.x;
        y: background-item.y;
        width: background-item.width;
        height: background-item.height;
    }
}
